name: CI/CD Pipeline

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew
    
    - name: Configurar ambiente Java
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Instalar dependências
      run: ./gradlew dependencies --info || true
    
    - name: Compilar código
      run: ./gradlew build --info || true

    - name: Executar testes
      run: ./gradlew test --info 

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: Deploy em ambiente de teste
      run: |
        # Adicione aqui os comandos de implantação em seu ambiente de teste
