name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar ambiente Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Instalar dependências
      run: ./gradlew dependencies --info

    - name: Compilar código
      run: ./gradlew build --info

    - name: Executar testes
      run: ./gradlew test --info

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: Deploy em ambiente de teste
      run: |
        # Adicione aqui os comandos de implantação em seu ambiente de teste
